[배남석]  사진 슬라이드 추가하기
softeerbootcamp-2nd/ios-keynote pull request #24
Opened 2023-07-27 01:28 UTC by NamSeok-Bae

# ios-keynote 3~4주차 프로젝트

## 사진 슬라이드 추가하기 (완료일 7/27 01:00)

### 주요 작업 내용

- Cell에 ContextMenuInteraction를 할당
- ImageSlideView에 원 탭, 투 탭 기능 할당
- ContextMenuInteraction의 메뉴에 따른 동작 구현
- UIGraphicsImageRenderer를 활용한 Image Resize
    - resize한 결과에 따라 ImageSlideView Size 재정의
- SlideFactory에서 Random Slide 생성

## 작업결과

### 사진 등록
<img width="100%" alt="image" src="https://github.com/team-dayeng/Dayeng/assets/76683388/2334c759-d0e4-4543-81a7-3f1dc0b4518b">

### 메뉴 4개를 통한 Slide 이동
<img width="100%" alt="image" src="https://github.com/team-dayeng/Dayeng/assets/76683388/01935822-51b6-4159-bb29-f8e9a65e915e">

## 고민
- UIView 내부에서 자그마한 로직들을 구현하면서 생긴 의문점이 있습니다.
- 어제 스쿼드 세션 뿐만 아니라 동료분들과 대화하면서 View 내부의 프로퍼티를 사용해 로직을 구현하는 과정을 Model에서 진행하는게 맞다고 생각하였습니다.
- 하지만 isTapped = !isTapped 또는 이런 비슷한 로직들을 위해 따로 ViewModel을 만들어서 주는게 맞는지, 하위 뷰의 1개의 로직만을 위한 ViewModel을 만드는게 맞는건지 고민이 있습니다.
- 제 생각엔 단순한 로직 같은 경우 Model을 만들고 binding을 해주는 것보다 View에서 처리하는게 맞다고 생각하는데, 어떤 것이 효율적인 성능을 이끌어내는지 궁금합니다.

2023-07-27 01:29 UTC, NamSeok-Bae commented on MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
> +    }
이 부분에 대해서 순수함수적으로 어떻게 나누어야할지 모르겠습니다.

sourceIndex 와 destinationIndex를 통해 move 할지 안할지 판단하는 함수를 따로 만들어서 할 수 있을 것이라 생각합니다.
하지만 아래에 있는 remove 와 insert는 검증된 메소드들인데 따로 순수함수로 구분해주어야하는지 의문입니다.

그리고 위 함수에서 매개변수로 항상 안전한 값들이 들어온다고 했을 때도 따로 유효처리를 해줘야하는지 의문입니다.

2023-07-27 01:30 UTC, godrm commented
> * 하지만 isTapped = !isTapped 또는 이런 비슷한 로직들을 위해 따로 ViewModel을 만들어서 주는게 맞는지, 하위 뷰의 1개의 로직만을 위한 ViewModel을 만드는게 맞는건지 고민이 있습니다.
> * 제 생각엔 단순한 로직 같은 경우 Model을 만들고 binding을 해주는 것보다 View에서 처리하는게 맞다고 생각하는데, 어떤 것이 효율적인 성능을 이끌어내는지 궁금합니다.

좋은 고민이네요. sli.do에도 남겨주세요 :)

2023-07-27 01:35 UTC, godrm commented on MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
> +    }
일단 여기서는 정상 흐름과 비정상 흐름만 구분한다고 하면 BOOL 타입을 리턴할 수 있겠죠
모든 함수가 꼭 리턴타입이 있어야 하는 건 아니지만, 정상 흐름과 비정상 흐름을 구분할 수 있도록 고려해보자는 의미입니다.

2023-07-27 02:11 UTC, godrm requested changes
이미지 다루는 부분은 수정을 하셔야 할 것 같아요
PR 열어놓겠습니다. 수정하고 푸시한 다음 알려주세요

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
> +           let slide = slideArray[index] as? SquareSlide {
여기서 배열에 있더라도 이렇게 타입 캐스팅을 하지 않고 사용할 수 있으면 좋을꺼 같아요. 다형성으로 동작할 수 있나 고민해보세요.

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/Model/Struct/DefaultSlideManager.swift
>      }
이 메소드는 검색해서 특정 인덱스를 선택하고 끝나는 건가요? 
search-로 시작해서 리턴값이 있을 것처럼 유추했는데 어색하네요. 
이 메소드를 테스트하려면 currentUseIndex 접근할 수 있어야 겠네요?

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/Util/Extension/UIImage+.swift
> +    }
이 메소드들은 UIImage에 필요한 게 아니라, SlideView와 관련된 메소드 같아요. 
이 파일이 아니라 뷰쪽에 선언하는 게 어떨까요?

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/View/SlideView.swift
> +    }
이 메소드는 구현이 안되어 있는 데 수퍼 클래스라서 그런건가요? 전혀 사용하지 않는 건가요? 
그러면 프로토콜로 처리해도 되지 않을까요?

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/View/SlideView.swift
>      }
`view.bindData(data: xxx)` 형태가 될텐데 data가 반복되서 조금 어색한 것 같습니다 
더구나 Data 라는 타입이 있다보니 그것과도 헷갈리구요. 조금더 구체적인 표현도 좋을 것 같습니다.

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/View/SlideView.swift
>      }
아래 bindData와 setupProperties가 같은 역할을 하는 것 같은데 어떤 차이가 있나요?

2023-07-27 02:11 UTC, godrm commented on MyKeynote/MyKeynote/View/SlideListCell.swift
bind 라는 함수를 사용하는데 어떤 의도인지 잘 모르겠습니다.
bind는 combine처럼 어떤 값과 어떤 값을 연결하거나 객체와 객체를 연결하는 메소드(또는 클로저) 느낌인데
여기서는 모두 그냥 뷰에 값을 넣는 함수인 것 같아서요.

2023-07-30 13:31 UTC, NamSeok-Bae commented
변경 완료하였습니다!

2023-08-09 02:43 UTC, merged